<?xml version="1.0"?>
<package format="3">
  <name>video_embedding</name>
  <version>3.11.0</version>
  <description>The video_embedding package</description>
  <maintainer email="petr.vanc@cvut.cz">Petr Vanc</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <build_depend>rclpy</build_depend>
  <build_export_depend>rclpy</build_export_depend>
  <exec_depend>rclpy</exec_depend>

  <depend>pynput</depend>

  <export>
    <build_type>ament_python</build_type>
  </export>

</package>



